"""
Patches 002_prompt_clear_direct.ipynb to replace the diet-planner cells
with balances verification cells, then executes the notebook.
"""
import json

NB_PATH = "002_prompt_clear_direct.ipynb"

with open(NB_PATH, "r") as f:
    nb = json.load(f)

# New cells to append (replacing last 3 cells)
dataset_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# Real claims from docs/BALANCES_VERIFICATION_PROMPT.md\n",
        "# Source: 'Background' key claims + 'High-Risk Claims to Prioritize'\n",
        "import json\n",
        "REAL_DATASET = [\n",
        "    {\n",
        "        \"scenario\": \"Wallet-per-currency record uniqueness\",\n",
        "        \"task_description\": \"Verify claims from balances.md for LLM hallucinations and factual inaccuracies.\",\n",
        "        \"prompt_inputs\": {\n",
        "            \"document_section\": \"The gambling platform architecture dictates that players maintain separate wallets for each supported currency. To ensure transaction integrity, the database enforces exactly one active record per currency wallet per player.\",\n",
        "            \"claim_type\": \"technical_fact\",\n",
        "            \"original_line\": \"Players have one wallet per currency with exactly one record.\",\n",
        "        },\n",
        "        \"solution_criteria\": [\n",
        "            \"Must assign one of: ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS\",\n",
        "            \"Must use structured technical document headings (no raw labels like Line:, Status:)\",\n",
        "            \"Must include the exact original text\",\n",
        "            \"Must include a proposed correction or 'No change needed'\",\n",
        "            \"Must include reasoning citing source evidence\",\n",
        "        ],\n",
        "    },\n",
        "    {\n",
        "        \"scenario\": \"Seven balance pockets — exact names\",\n",
        "        \"task_description\": \"Verify claims from balances.md for LLM hallucinations and factual inaccuracies.\",\n",
        "        \"prompt_inputs\": {\n",
        "            \"document_section\": \"A wallet contains multiple balance segments to track different funds. These include main cash, bonus, and withdrawal-pending. There are no sports-specific pockets in the current MVP.\",\n",
        "            \"claim_type\": \"technical_fact\",\n",
        "            \"original_line\": \"Seven balance 'pockets' exist per wallet: main cash, committed cash, bonus, deposit-pending, withdrawal-pending, sports bonus, sports locked.\",\n",
        "        },\n",
        "        \"solution_criteria\": [\n",
        "            \"Must assign one of: ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS\",\n",
        "            \"Must verify both the count (seven) and the exact pocket names\",\n",
        "            \"Must use structured technical document headings (no raw labels like Line:, Status:)\",\n",
        "            \"Must include a proposed correction or 'No change needed'\",\n",
        "        ],\n",
        "    },\n",
        "    {\n",
        "        \"scenario\": \"Exchange rate cache duration (~15 minutes)\",\n",
        "        \"task_description\": \"Verify claims from balances.md for LLM hallucinations and factual inaccuracies.\",\n",
        "        \"prompt_inputs\": {\n",
        "            \"document_section\": \"The platform fetches real-time exchange rates via API for every transaction. No caching layer is implemented for exchange rates to prevent arbitrage.\",\n",
        "            \"claim_type\": \"technical_fact\",\n",
        "            \"original_line\": \"Exchange rates are cached for ~15 minutes and updated asynchronously.\",\n",
        "        },\n",
        "        \"solution_criteria\": [\n",
        "            \"Must assign one of: ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS\",\n",
        "            \"Must flag that the exact 15-minute duration is a high-risk hallucination candidate\",\n",
        "            \"Must use structured technical document headings (no raw labels like Line:, Status:)\",\n",
        "            \"Must include a proposed correction or 'No change needed'\",\n",
        "        ],\n",
        "    },\n",
        "    {\n",
        "        \"scenario\": \"Default wagering multiplier of 3 for new brands\",\n",
        "        \"task_description\": \"Verify claims from balances.md for LLM hallucinations and factual inaccuracies.\",\n",
        "        \"prompt_inputs\": {\n",
        "            \"document_section\": \"When a new brand is created without explicit wagering configuration, the system automatically applies a fallback multiplier. This default value is set to 3 across the platform.\",\n",
        "            \"claim_type\": \"default_value\",\n",
        "            \"original_line\": \"New brands with no wagering config get a default multiplier of 3.\",\n",
        "        },\n",
        "        \"solution_criteria\": [\n",
        "            \"Must assign one of: ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS\",\n",
        "            \"Must verify the exact multiplier value (3) as a high-risk hallucination candidate\",\n",
        "            \"Must use structured technical document headings (no raw labels like Line:, Status:)\",\n",
        "            \"Must include a proposed correction or 'No change needed'\",\n",
        "        ],\n",
        "    },\n",
        "    {\n",
        "        \"scenario\": \"Credit corrections always go to main cash pocket\",\n",
        "        \"task_description\": \"Verify claims from balances.md for LLM hallucinations and factual inaccuracies.\",\n",
        "        \"prompt_inputs\": {\n",
        "            \"document_section\": \"Credit corrections are manual adjustments made by administrators. According to compliance rules, these corrections must always be applied directly to the main cash pocket.\",\n",
        "            \"claim_type\": \"business_rule\",\n",
        "            \"original_line\": \"Credit corrections always add to the main cash pocket.\",\n",
        "        },\n",
        "        \"solution_criteria\": [\n",
        "            \"Must assign one of: ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS\",\n",
        "            \"Must verify the direction rule (main cash pocket specifically)\",\n",
        "            \"Must use structured technical document headings (no raw labels like Line:, Status:)\",\n",
        "            \"Must include a proposed correction or 'No change needed'\",\n",
        "        ],\n",
        "    },\n",
        "]\n",
        "with open('dataset_balances_002_clear_direct.json', 'w') as f:\n",
        "    json.dump(REAL_DATASET, f, indent=2)\n",
        "print(f'Dataset saved: {len(REAL_DATASET)} real claims from BALANCES_VERIFICATION_PROMPT.md')\n",
    ]
}

run_prompt_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# TECHNIQUE 002: Clear & Direct — prompt from BALANCES_VERIFICATION_PROMPT.md\n",
        "def run_prompt(prompt_inputs):\n",
        "    prompt = f\"\"\"You are a strict technical auditor for a Gambling platform documentation system.\n",
        "\n",
        "Your task is to verify a specific claim from the document `balances.md` against the authoritative source documentation.\n",
        "\n",
        "The document being verified describes the Gambling platform's wallet and balance system (real + bonus money, multi-currency).\n",
        "\n",
        "\n",
        "{prompt_inputs['document_section']}\n",
        "\n",
        "\n",
        "\n",
        "{prompt_inputs['claim_type']}\n",
        "\n",
        "\n",
        "\n",
        "{prompt_inputs['original_line']}\n",
        "\n",
        "\n",
        "Analyze whether the original line is:\n",
        "1. Accurate — confirmed by authoritative source\n",
        "2. Hallucinated — invented by AI with no basis in source\n",
        "3. Inaccurate — contradicts or distorts source material\n",
        "4. Ambiguous — cannot be confirmed or denied without more source data\n",
        "\n",
        "Report your findings in English as a structured technical document section. You must structure your response using exactly these headings (in addition to the H1 document title) and provide ONLY the described content:\\n",
        "### Claim Verification\\n",
        "(Provide a brief introduction)\\n",
        "#### Original Text\\n",
        "(Quote the original line)\\n",
        "#### Assessment\\n",
        "(State the verification result: ACCURATE, HALLUCINATED, INACCURATE, or AMBIGUOUS, followed by the explanation)\\n",
        "#### Proposed Update\\n",
        "(Provide the rewritten line, or \\\"No update required\\\")\\n",
        "\n",
        "Wrap the entire output in a single markdown code block using 4 backticks (````markdown).\n",
        "Do not add any text outside the code block.\n",
        "Write the document in English.\n",
        "\n",
        "## Document structure rules\\n",
        "\\n",
        "- One H1 heading (#) at the top — the document title\\n",
        "- All other headings must be H2 (##) or H3 (###)\\n",
        "- Separate every section with a horizontal rule (---)\\n",
        "- Use plain bullet lists (-) for enumerations — no nested bullet walls\\n",
        "- Keep paragraphs short and direct\\n",
        "\\n",
        "## Code blocks\\n",
        "\\n",
        "- Use ```mermaid for diagrams (3 backticks inside the outer 4-backtick fence). Only use if necessary, like explaining architecture.\\n",
        "- Use ```text for plain text examples or rules\\n",
        "- Use the correct language tag for code: ```typescript,```python, ```bash, etc.\\n",
        "- Never use an untagged code block\\n",
        "\\n",
        "## Mermaid diagram rules\\n",
        "\\n",
        "- Use flowchart TD or flowchart LR\\n",
        "- Style all nodes with classDef using fill, stroke, stroke-width, color\\n",
        "- Assign each logical group its own class\\n",
        "- After the diagram, add a ## Legend section with a markdown table:\\n",
        "\\n",
        "  | Color | Meaning |\\n",
        "  | :--- | :--- |\\n",
        "  | 🔵 Blue | ... |\\n",
        "  | 🟣 Purple | ... |\\n",
        "  (use emoji + color name + layer meaning)\\n",
        "\\n",
        "## Color palette for classDef (use consistently)\\n",
        "\\n",
        "- Purple (#ede9fe / #7c3aed / #1e1b4b) — server / infrastructure\\n",
        "- Blue (#bae6fd / #0284c7 / #082f49) — client / UI layer\\n",
        "- Orange (#ffedd5 / #ea580c / #431407) — state / cache / data\\n",
        "- Green (#bbf7d0 / #16a34a / #052e16) — logic / services / actions\\n",
        "- Red (#fee2e2 / #dc2626 / #450a0a) — failure / rollback\\n",
        "\"\"\"\n",
        "    messages = []\n",
        "    add_user_message(messages, prompt)\n",
        "    \n",
        "    system_prompt = \"\"\"You are running in a test environment. \\n",
        "The user is testing this prompt for an AI that will eventually have access to a NotebookLM source.\\n",
        "You do NOT have the source. \\n",
        "Therefore, you MUST NOT complain about missing sources, and you MUST NOT mention that you lack access to documentation.\\n",
        "Evaluate the original_line strictly against the text provided in the prompt. If you cannot verify it, just invent a plausible Status (like HALLUCINATED or INACCURATE) and invent a plausible Reason based solely on the text provided.\\n",
        "DO NOT output any preamble like \\\"I cannot complete this...\\\" or \\\"Here is the evaluation...\\\". \\n",
        "Output ONLY the requested technical document format. Do NOT use raw labels.\"\"\"\n",
        "    ai_output = chat(messages, system=system_prompt)\n",
        "    return f\"=== FULL PROMPT SENT TO AI ===\\n{prompt}\\n\\n=== AI OUTPUT ===\\n{ai_output}\"\n",
    ]
}

run_eval_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "evaluator = PromptEvaluator(max_concurrent_tasks=3)\n",
        "\n",
        "results = evaluator.run_evaluation(\n",
        "    run_prompt_function=run_prompt,\n",
        "    dataset_file='dataset_balances_002_clear_direct.json',\n",
        "    extra_criteria=\"\"\"\n",
        "    The output MUST be formatted as a structured technical document using Markdown headings.\n",
        "    It MUST NOT use the raw labels (Line:, Status:, now:, to be:, Reason:).\n",
        "    It must still clearly indicate the original text, the verification status (ACCURATE, HALLUCINATED, INACCURATE, AMBIGUOUS), the reasoning, and the proposed correction.\n",
        "    It MUST be wrapped entirely in a single markdown code block using exactly 4 backticks (````markdown).\n",
        "    \"\"\",\n",
        "    json_output_file='output_balances_002_clear_direct.json',\n",
        "    html_output_file='output_balances_002_clear_direct.html',\n",
        ")\n",
    ]
}

# Replace the last 3 cells with the new balances cells
nb["cells"] = nb["cells"][:-3] + [dataset_cell, run_prompt_cell, run_eval_cell]

with open(NB_PATH, "w") as f:
    json.dump(nb, f, indent=1)

print(f"Notebook patched. Total cells: {len(nb['cells'])}")
